---
title: "Figure S6 - Parahippocampal fMRI Activity vs. Tau Burden"
author: "Tom Morin"
date: "2024-07-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load Libraries
library(tidyverse)
library(ggpubr)
library(lme4)
library(lmerTest)
library(rstatix)

# Set colorscales
jack_status_cscale <- scale_color_manual(values = c("#549e3e", "#323690", "#B6357B"))
jack_status_fscale <- scale_fill_manual(values = c("#549e3e", "#323690", "#B6357B"))

df <- read_csv('data_sup_fig06.csv')
df$tau_status <- factor(df$tau_status, levels = c('Younger\nAdults', 'Tau-', 'Tau+'))
```

## Plot Panel A: Braak III/IV FTP vs. Parahippocampal fMRI (Remembered vs. Forgotten)
```{r, echo = FALSE}
figA <- df %>%
  ggplot(aes(x = ftp_braak34_suvr, y = bold)) +
  geom_point() +
  geom_smooth(method = 'lm', limit = 0.9, linewidth = 2) +
  theme_classic() +
  xlab(bquote('[18F]FTP SUVR\n(Braak 3/4 Regions)')) +
  ylab('fMRI Beta Coefficient\n(Remembered vs. Forgotten)') +
  theme(panel.background = element_blank(),
      axis.line = element_line(color = 'black'),
      legend.position = 'none', 
      axis.text.x = element_text(color = 'black', size = 8),
      axis.text.y = element_text(color = 'black', size = 8),
      axis.title.x = element_text(color = 'black', size = 10),
      axis.title.y = element_text(color = 'black', size = 10),
      legend.title = element_blank(),
      aspect.ratio = 1)

figA
```

## Linear Models: Effect of Tau Burden and Biomarker Group on BOLD signal contrast
```{r, echo = FALSE}
# Stats for Panel A
# Just older adults, simple model
lm1 <- lm(bold ~ ftp_braak34_suvr + age + sex + yrs_edu, 
          data = df %>% filter(!is.na(ftp_braak34_suvr)))
print('==========================================================================')
summary(lm1)
print('==========================================================================')

lm2 <- lm(bold ~ ftp_braak34_suvr*biomarker_group + age + sex + yrs_edu, 
          data = df %>% filter(!is.na(ftp_braak34_suvr)))
print('==========================================================================')
summary(lm2)
print('==========================================================================')
```

## Plot Panel B: FMT vs. fMRI by Tau Burden
```{r, echo = FALSE}
# Panel B
figB <- df %>% filter(! is.na(tau_status)) %>%
  ggplot(aes(x = fmt_ki_vst, y = bold, group = tau_status, 
             color = tau_status, fill=tau_status)) +
  geom_point(alpha = 0.5) +
  geom_smooth(method = 'lm', limit = 0.9, linewidth = 2) +
  scale_fill_manual('[18F]FTP Status', values = c("#549e3e", "#323690", "#B6357B")) +
  scale_color_manual('[18F]FTP Status', values = c("#549e3e", "#323690", "#B6357B")) +
  theme_classic() +
  xlab(bquote('[18F]FMT Ki\n(Ventral Striatum)')) +
  ylab('fMRI Beta Coefficient\n(Remembered vs. Forgotten)') +
  theme(panel.background = element_blank(),
      axis.line = element_line(color = 'black'),
      #legend.position = 'none', 
      axis.text.x = element_text(color = 'black', size = 8),
      axis.text.y = element_text(color = 'black', size = 8),
      axis.title.x = element_text(color = 'black', size = 10),
      axis.title.y = element_text(color = 'black', size = 10),
      aspect.ratio = 1)

figB
```

## Linear Model: Test for interaction of FMT and Tau Burden on fMRI signal
```{r, echo = FALSE}
lm3 <- lm(bold ~ ftp_braak34_suvr*fmt_ki_vst + age + sex + yrs_edu, 
          data = df %>% filter(!is.na(ftp_braak34_suvr)))
print('==========================================================================')
summary(lm3)
print('==========================================================================')
```

## Repeat analysis, accounting for learning performance
```{r, echo = FALSE}
lm4 <- lm(bold ~ ftp_braak34_suvr*fmt_ki_vst + learning_total + age + sex + yrs_edu, 
          data = df %>% filter(!is.na(ftp_braak34_suvr)))
print('==========================================================================')
summary(lm4)
print('==========================================================================')
```

## Plot entire Figure S6:
```{r, echo = FALSE}
fmri_mem <- ggarrange(figA, figB, 
          ncol = 2, 
          labels = c('A', 'B'),
          widths = c(0.6, 1))

ggsave(fmri_mem, filename = 'sup_fig06.pdf', width = 6, height = 3, units = 'in')
fmri_mem
```
