---
title: "Memory by Confidence"
author: "Tom Morin"
date: "2025-04-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load libraries
library(tidyverse)
library(ggplot2)
library(dplyr)
library(emmeans)

# Set colorscales
age_group_cscale <- scale_color_manual(values = c("#643f95", "#549e3e"))
age_group_fscale <- scale_fill_manual(values = c("#643f95", "#549e3e"))

# Read in data
df <- read_csv('anon_dprime_by_conf.csv')

df$valence <- factor(df$valence, levels = c('Loss', 'Neutral', 'Reward'))
```

## Plot figure S8: Memory by age/valence/confidence
```{r, echo = FALSE}
# Plot dprime for OAs and YAs across Valence and Confidence Level
fig <- df %>%
  ggplot(aes(x=valence, y=dprime, fill=age_group, color=age_group)) +
  geom_hline(yintercept=0) + 
  geom_point(aes(x=valence, y=dprime), alpha = 0.5, position = position_dodge(0.8)) +
  stat_summary(fun.y = "mean", geom="bar", size=1, width=0.75, position=position_dodge(0.8), alpha=0.5) +
  stat_summary(fun.data = mean_se, geom="errorbar", width=0.3, size=1, position=position_dodge(0.8)) +
  labs(title="Dprime by Confidence Level") +
  age_group_cscale +
  age_group_fscale +
  xlab("") +
  ylab("dprime") +
  facet_wrap(.~confidence) +
  theme(panel.background = element_blank(), 
        axis.line = element_line(colour = "black"), 
        legend.position = "bottom", 
        axis.text.x = element_text(colour = "black", size = 12), 
        axis.text.y = element_text(colour = "black", size = 12)) +
  scale_y_continuous(expand = expansion(mult = c(0.1,0.1)))
fig

ggsave('sup_fig08.pdf', fig)
```

## Linear model and posthoc t-tests
```{r, echo = FALSE}
mod <- lm(dprime ~ confidence*age_group*valence, 
          data = df)
summary(mod)

emm = emmeans(mod, ~ confidence*age_group*valence)
pairs(emm, simple = 'each', adjust = "none")

dsum <- df %>% group_by(valence, confidence, age_group) %>% summarize(
  dprime_mean = mean(dprime, na.rm = TRUE),
  dprime_std = sd(dprime, na.rm = TRUE),
  dprime_est = (t.test(dprime, na.rm = TRUE)$estimate),
  dprime_T = (t.test(dprime, na.rm = TRUE)$statistic),
  dprime_p = (t.test(dprime, na.rm = TRUE)$p.value))
dsum
```